# Schema for the configuration files of the Дополнительные поля module.
additional_field.settings:
  type: config_object
  label: 'Дополнительные поля settings'
  mapping:
    phone_number:
      type: tel
      label: ''
    mail:
      type: email
      label: ''
    address:
      type: string
      label: ''
    additional_info:
      type: string
      label: ''
    table:
      type: table
      label: ''
